services:
  nginx:
    build:
      context: ./repositories/nginx
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-nginx:latest"
    ports:
      - "4000:5000"
    volumes:
      - ./repositories/nginx/nginx.conf:/etc/nginx/nginx.conf
    profiles:
      - default
      - build

  api:
    build:
      context: ./repositories/api
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-api:latest"
    ports:
      - "4001:5000"
    profiles:
      - default
      - build
    depends_on:
      - mysql
    volumes:
      - ./repositories/api/bin/server.dart:/app/bin/server.dart
      - ./repositories/api/lib:/app/lib
      - ./repositories/api/test:/app/test

  web:
    build:
      context: ./repositories/web
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-web:latest"
    ports:
      - "4002:5000"
    profiles:
      - default
      - build
    volumes:
      - ./repositories/web:/app
  mysql:
    image: "mysql:8.4.4"
    ports:
      - "4003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: flimsy
      MYSQL_DATABASE: url_shortener
    profiles:
      - default
      - build
