networks:
  url_shortener:
    driver: bridge

services:
  nginx:
    build:
      context: ./repositories/nginx
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-nginx:latest"
    restart: on-failure:5
    ports:
      - "${NGINX_EXTERNAL_PORT:-4000}:${NGINX_INTERNAL_PORT:-5000}"
    volumes:
      - ./repositories/nginx/nginx.conf:/etc/nginx/nginx.conf
    profiles:
      - default
      - build
    environment:
      - PORT="${NGINX_INTERNAL_PORT:-5000}"
    networks:
      - url_shortener

  api:
    build:
      context: ./repositories/api
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-api:latest"
    restart: on-failure:5
    ports:
      - "${API_EXTERNAL_PORT:-4001}:${API_INTERNAL_PORT:-5000}"
      - 8181:8181
    profiles:
      - default
      - build
    depends_on:
      - mysql
      - nginx
    volumes:
      - ./repositories/api/bin/server.dart:/app/bin/server.dart
      - ./repositories/api/bin/injector.dart:/app/bin/injector.dart
      - ./repositories/api/lib:/app/lib
      - ./repositories/api/test:/app/test
    environment:
      - HOST=${API_HOST:-localhost}
      - PORT=${API_INTERNAL_PORT:-5000}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-url_shortener}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_INTERNAL_PORT:-3306}
      - ENV=${ENV:-production}
      - CREATE_KEY=${CREATE_KEY:-supersecret}
      - PASSWORD_KEY=${PASSWORD_KEY}
      - HASH_ROUNDS=${API_HASH_ROUNDS:-5}
      - MYSQL_USER=${MYSQL_USER:-mysql}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-flimsy}
    networks:
      - url_shortener

  web:
    build:
      context: ./repositories/web
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-web:latest"
    restart: on-failure:5
    ports:
      - "${WEB_EXTERNAL_PORT:-4002}:${WEB_INTERNAL_PORT:-5000}"
    profiles:
      - default
      - build
    volumes:
      - ./repositories/web:/app
    depends_on:
      - api
      - nginx
    networks:
      - url_shortener

  mysql:
    image: "mysql:8.4.4"
    restart: on-failure:5
    user: root
    ports:
      - "${MYSQL_EXTERNAL_PORT:-4003}:${MYSQL_INTERNAL_PORT:-3306}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-flimsy}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-flimsy}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-url_shortener}"
      MYSQL_USER: "${MYSQL_USER:-mysql}"
    profiles:
      - default
      - build
    expose:
      - "${MYSQL_INTERNAL_PORT:-3306}"
    depends_on:
      - nginx
    volumes:
      - mysql-data:/var/lib/mysql:rw
    command: --max_connections=1000 --wait_timeout=28800 --interactive_timeout=28800
    networks:
      - url_shortener

volumes:
  mysql-data:
