services:
  nginx:
    build:
      context: ./repositories/nginx
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-nginx:latest"
    ports:
      - "4000:5000"
    volumes:
      - ./repositories/nginx/nginx.conf:/etc/nginx/nginx.conf
    profiles:
      - default
      - build

  api:
    build:
      context: ./repositories/api
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-api:latest"
    ports:
      - "4001:5000"
    profiles:
      - default
      - build

  web:
    build:
      context: ./repositories/web
      dockerfile: Dockerfile
    image: "docker.io/ojsung93/url-shortener-web:latest"
    ports:
      - "4002:5000"
    profiles:
      - default
      - build
    volumes:
      - ./repositories/web:/app

