name: url_shortener_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.7.1

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  get_it: ^8.0.3
  mysql_client: ^0.0.27
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
