import 'package:url_shortener_server/shared/multi_part_string.dart';

abstract class AuthService {
  /// Accepts the username and userId and generates an authentication token to be used as the authorization header
  /// The token is generated by hashing the username with a key that is generated each minute and stored for an hour
  /// Authorization tokens are thus only valid for one hour
  String generateAuthToken(String username, int userId);
  /// Accepts a token and a userId and regenerates the token to verify that it is valid
  Future<bool> verifyAuthToken(String token, int userId);
  /// Same as above, but accepts an already-hashed password and user id
  Future<bool> verifyPasswordById(String password, int userId);
  /// Accepts a plain-text password and hashes it to verify it against a stored hash
  bool verifyPassword(String hash, String password);
  /// Hash a password using the key stored in the environment
  MultiPartString hashPassword(String password);
}
